load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "parallelTest_header",
    hdrs = [
        "ParallelTest.h",
        "ParallelTest.h.in",
    ],
    includes = [
        ".",
    ],
    deps = [
        "//:Parallel",
    ],
)
